run-dev:
# @echo is used to print the message to the console
	@echo "Loading environment variables from .env..."
# @export is used to set the environment variables in the current shell
	@export VIRTUAL_ENV=$(PWD)/.venv && uv run python run.py

